version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: frost
      POSTGRES_PASSWORD: qazx
      POSTGRES_DB: postgres_db    
    ports:
      - "5432:5432"
   
    command: postgres 
    restart: always 
  redis:
    image: redis:alpine3.14
    container_name: redis-container
    ports:
      - "6379:6379"


     
  